### PR TITLE
update `connect` doc

### PR DESCRIPTION
**Pull request by zburke**
Fixes [STCON-61](https://issues.folio.org/browse/STCON-61)

### CODE REVIEW

**Comment by MikeTaylor** [comment]
In your updated code sample, you have
```
       export connect(Widget);
```
Can you do that? Don't you still need to do
```
       export stripes.connect.connect(Widget);
```
?

**Comment by zburke** [comment]
I don't think that's necessary as `connect` is exported by `stripes-components/connect.js` so there is no reason to access it through `stripes.connect`. (Is `stripes` even available in that scope?)

**Comment by MikeTaylor** [comment]
What is this `stripes-components/connect.js` of which you speak? I can find no file anywhere in stripes-components with "connect" in its name.

**Comment by zburke** [comment]
Sorry; `stripes-connect/connect.js`.

**Comment by MikeTaylor** [comment]
Right, but that is the uncurried "base" connect function, which _does_ need the module-name to be passed in as the second argument. The function provided on the Stripes object has been curried to include the appropriate module-name (because the specific Stripes object is constructed to be used by that module).

**Comment by zburke** [comment]
Right you are. I so rarely see components connecting themselves in the `export connect(...)` manner, but rather parents connecting child components, that I forgot it was different. Thanks for the sharp eyes and the clear explanation. 

I'll push up a new PR that demonstrates use of the curried function from stripes, as well as dataKey, without _breaking_ the perfectly accurate documentation that you already put in place.

**Comment by MikeTaylor** [comment]
That is a very charitable summary of where we landed.

Another valid summary would have been, "Mike, you should have updated the stripes-connect documentation way back when the curried function was first added to the Stripes object."

**Pull request closed without merging**
