### PR TITLE
Replace data with resources in componentShouldRefreshRemote. Fixes STCON-38

### PR DESCRIPTION
**Pull request by mkuklis**

### CODE REVIEW

**Comment by funkymalc** [comment]
looks like eslint reported an error in this PR.   See build details.

**Comment by mkuklis** [comment]
Thanks @funkymalc!

**Comment by mkuklis** [comment]
@MikeTaylor the `LocalResource` doesn't use `records`. Also it looks like `data` prop is still referenced in couple places in `RESTResource` so I didn't want remove it just yet.

**Comment by MikeTaylor** [comment]
If the `data` prop is still references, that is a bug and it will not work.

**Comment by mkuklis** [comment]
Mike the data references are just left over from 111 work @skomorokh did. For example: 
https://github.com/folio-org/stripes-connect/blob/master/RESTResource/RESTResource.js#L93

Perhaps you are right and we should wait for Jason to finalize it. I created this PR because it currently causing couple issues related to refreshing.

**Comment by MikeTaylor** [comment]
> Mike the data references are just left over from 111 work @skomorokh did. For example:
https://github.com/folio-org/stripes-connect/blob/master/RESTResource/RESTResource.js#L93

But Jason has subsequently removed _all_ support for the `data` attribute, which has been deprecated for some time. All references to it ought to have been replaced by references to `resources` -- right, @skomorokh?

**Comment by mkuklis** [comment]
Yes I think that's the case too. These can be probably safely removed but let's wait for Jason to confirm :)

**Comment by mkuklis** [comment]
That Jason guy is a nice guy :)

**Pull request merged**
