### PR TITLE
Refresh resource with interpolated property when the prop changes. Fixes STCON-81.

### PR DESCRIPTION
**Pull request by mkuklis**
The refresh was not handled for resources with paths defined as `!{prop}`. This PR should address it.

https://issues.folio.org/browse/STCON-81

### CODE REVIEW

**Comment by mkuklis** [comment]
Hey @OleksandrYehorovEPAM would you mind giving this a try with your current setup and see if it works without the refreshRemote hack here: 
https://github.com/folio-org/stripes-smart-components/pull/539

Thank you!

**Comment by OleksandrYehorovEPAM** [comment]
> Hey @OleksandrYehorovEPAM would you mind giving this a try with your current setup and see if it works without the refreshRemote hack here:
> [folio-org/stripes-smart-components#539](https://github.com/folio-org/stripes-smart-components/pull/539)
> 
> Thank you!

Sure, I will check.

**Comment by mkuklis** [comment]
Thank you both for reviewing this. @MikeTaylor brilliant idea about polymorphic approach! I just refactored it a bit and it looks much cleaner. Thanks!

**Comment by MikeTaylor** [comment]
How utterly bizarre that, after making this unambiguous improvement, the "quality" gate rejects the code.

**Comment by MikeTaylor** [comment]
Can we please find a way to get this merged? The bug is a real issue.

**Comment by doytch** [comment]
@mkuklis 's on holiday so I just pushed the magic button, coverage be damned.

**Comment by MikeTaylor** [comment]
Oh, cool — I didn't realise we had that option!

**Pull request merged**
