### PR TITLE
STCON-133: Move initResources to useEffect

### PR DESCRIPTION
**Pull request by mkuklis**
https://issues.folio.org/browse/STCON-133

When working on refactoring `connect` to use a functional component I tried to keep the lifecycle methods as close as possible to what we had in class based approach. In class based approach `initResources` was initialized in the constructor (before the first render). This is hard to express in a functional component and it was a main reason why I introduced `useComponentWillMount` hook. Unfortunately react does not like this approach and it throws:

````
Warning: Cannot update a component (`Connect(WithConnect(Wrapper))`) while rendering a different component (`Wrapper`). To locate the bad setState() call inside `Wrapper
````

This was discovered originally by @MikeTaylor:

https://folio-project.slack.com/archives/C210UCHQ9/p1647877882082549

The reason for this is because `initResources` is modifying a global redux state via:

https://github.com/folio-org/stripes-core/blob/fc3859fecd2a7deb2f4326e4be14bc75e0fd9fc1/src/components/Root/Root.js#L87

This PR moves the `initResources` to `useEffect` which seems to still work just fine and it should remove the ugly warning.

### CODE REVIEW

**Comment by mkuklis** [comment]
@MikeTaylor I would appreciate if you could give it a try with your setup and see if everything still works fine. You should be able to test it out in a workspace by cloning your ui module and stripes-connect and switching it to `STCON-133` branch.

**Comment by MikeTaylor** [comment]
I am not using a workspace at all. I am running my app stand-alone, and manually replacing `node_modules/@folio/stripes-connect` with a git checkout on the STCON-133 branch. This is the same approach I just used, successfully, to verify that https://github.com/folio-org/stripes-components/pull/1768 fixed the console warning that was previously being generated.

**Comment by MikeTaylor** [comment]
Hmm, hold on, though: I modified my branch-STCON-133 checkout of stripes-connect to `console.log` in the useEffect, and I am not seeing any output. So it looks like some species of pilot error is involved.

**Review by zburke — APPROVED** [review]
LGTM! 

Is there any value in explaining the eslint-disable comment for that `useEffect(() => {...}, [])` block, i.e. why we don't care about potential new values for `context`, `props`, and `refreshRemote` because this is just an initialization function? If there's a legit argument that `useEffect(..., [])` already implies that, that's fine by me.

**Comment by mkuklis** [comment]
@zburke good idea about adding the docs around the `useEffect`. I will add it. We only want that `useEffect` to execute once.

**Comment by BogdanDenis** [comment]
@mkuklis I think this might have caused a race condition in `ui-quick-marc` when using `LocalResource`.
In quickMARC we have a component that calls different endpoints based on what type of record we're editing:
https://github.com/folio-org/ui-quick-marc/blob/master/src/QuickMarcEditor/QuickMarcEditorContainer.js#L159
And to form the url we're using a local resource `externalInstanceApi`
When this component is mounted we update that local resource to store a correct endpoint which is later used to get an instance record.

The issue is that `useEffect` in quickMARC is called before `useEffect` in `connect` so the resources are not initialized and actions are not processed by reducer.
If there's a better way of using a dynamic url to fetch records that doesn't require local resources - I'd be happy to use it instead of what we've come up with.
Otherwise I think we'll need to fix this in `stripes-connect`. Perhaps a queueing system to store actions before a reducer is registered and then dispatching them? Or introduce a new method on `LocalResource` - `ready` that will turn a promise that resolves when a resource is registered?

**Comment by mkuklis** [comment]
@BogdanDenis thanks for reporting this. I haven't seen this pattern before (using local resource as a part of path). But I think it's a valid one. I think perhaps one way to go around it would be to check if `externalInstanceApi._path` is present inside your useEffect here: https://github.com/folio-org/ui-quick-marc/blob/master/src/QuickMarcEditor/QuickMarcEditorContainer.js#L86 and add it as a dependency here: https://github.com/folio-org/ui-quick-marc/blob/master/src/QuickMarcEditor/QuickMarcEditorContainer.js#L116

**Comment by BogdanDenis** [comment]
@mkuklis unfortunately adding `externalInstanceApi._path` to deps didn't help, because `update` is still called before a reducer has been added, but thanks for your suggestion
But I tried simply calling ```GET({ path: `template_here` })``` and it worked...don't know why we didn't implement it like this initially
I think we should bump the major version, like you said

**Comment by MikeTaylor** [comment]
If you bump a major version, pepole will surely just stay with the old known-to-work version that doesn't require work to upgrade for no payoff.

**Comment by MikeTaylor** [comment]
I am finding at the moment that when stripes-connect calls fail, and I get the popup explaining what went wrong, the app then crashes in stripes-connect. I know this is a horribly vague report (I don't have access to details right now) but could this be the same thing manifesting differently?

**Pull request merged**
