### PR TITLE
 Initial work on "accumulate" manifest option with "GET" action STCON-33

### PR DESCRIPTION
**Pull request by skomorokh**
# An option for Okapi resources to accumulate records

If you set `accumulate: true` in your manifest, stripes-connect will offer
two additional actions on the (soon to be moved/renamed) props.mutator
object: `GET()` and `reset()`. It will also no longer automatically fetch
any records, instead, you trigger a fetch by calling GET and any records
returned are appended to the resource. It returns a promise that resolves to
an array of records. Optionally, you can specify a parameter in the same
format as the manifest options (eg. `{ path: 'users'   params: { query:
'water' } }`). reset() clears the resource.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
I really hope they don't -- that only a _very few_ people appreciate this new option. Because if a lot of people use it, that will show that we've not managed to convey what stripes-connect is about. Almost everyone, on joining this project, has a natural tendency to want to keep doing things the way they've been used to in other web-apps: explicitly fetching data. I've felt that we're in  constant battle to show people "No, look, that's not how we do things, there's a better way". The new GET accessor drives a big hole through that. I'm not saying we don't need it -- I'm sure Jason weighed all this up before adding it -- but I do think that each use of it is to be lamented as an imperfection. Just like every GOTO that a former FORTRAN programmer writes in a C program is to be lamented.

**Comment by MikeTaylor** [comment]
(To be 100% clear: none of that should be taken to mean that I think the PR should not have been accepted. That is _not_ what I was saying.)

**Comment by mkuklis** [comment]
@MikeTaylor I mostly agree with you. By "a lot of people" I meant those who ran into `stripes-connect` limitations :)

**Comment by nielserik** [comment]
Michal has by now been able to migrate both ui-checkout and ui-checkin to "stripes-connect clean" modules, using this feature. Something none of us seemed able to accomplish otherwise with previous versions of stripes-connect. 

That's one way of evaluating the feature.

**Comment by MikeTaylor** [comment]
Good call.

**Comment by zburke** [comment]
Updated the API documentation with details about this option in #25.

**Pull request merged**
