### PR TITLE
Introduce side effects. STRIPES-394

### PR DESCRIPTION
**Pull request by mkuklis**
This PR introduces side effects together with some code refactoring mainly to cleanup `connect.js`. 
Here are couple details about the current side effects setup:

1. They are based on redux-observable 
2. They refresh related resources after mutation happens
3. The resources which will be refreshed have to be `visible` and match the path of the resource from where the mutation originates.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
Woah! Radical change to the way the source files are organised!

I don't think it's a bad thing to do; but by doing this as part of the same PR as a significant change to what the code _does_, you've made it impossible to see the latter -- the diffs are absorbed.

So I don't really have any option but to blindly accept the PR.

**Comment by mkuklis** [comment]
@MikeTaylor I agree and I think I'm going to move all the refactoring back to what it was and just keep the side effects in.

**Comment by mkuklis** [comment]
Also this PR may actually go away completely if we introduce a new package for side effects.

**Comment by MikeTaylor** [comment]
Thanks, Michal, that's very gracious.

**Comment by mkuklis** [comment]
I'm going to close this PR and open another one which should be easier to review.

**Pull request closed without merging**
