### PR TITLE
STCON-76  Option#2: core circular dependency withConnect

### PR DESCRIPTION
**Pull request by JohnC-80**
Hot on the heels of  #79 , This PR involves bringing the 'rootContext' over to the `stripes-connect` side of the line.
## Pros
- No breaking changes (if merged in close proximity to the stripes-core PR)
- Local HOC's/Contexts get needed for tests for either case.

## Cons
- There can now be only one `stripes-connect` in the platform, due to the use of new Context API.

### CODE REVIEW

**Comment by JohnC-80** [comment]
Tests are failing here, of course, because `stripes-connect` doesn't provide the Connect Context in its current state...

**Comment by skomorokh** [comment]
How unsurprisingly circular :)

**Comment by JohnC-80** [comment]
Not exactly sure what SonarCube's wanting me to do here... all the new code seems to be running in the test set up, and tests pass in Jenkins across the board...

**Comment by skomorokh** [comment]
It seems connect isn't offering it coverage metrics and it is demanding that we not merge anything into connect until we feed it somehow. "0.0% Coverage (0.0% Estimated after merge)"

**Comment by zburke** [comment]
SonarCube is failing because it wants to see 80% test coverage of new code. Sadly, I have no idea how to write a test for this :( We _can_ still merge without passing through that "quality gate", but it would be great if we could figure add the coverage. If somebody wants to walk me through it, I'm happy to help write additional tests.

**Comment by skomorokh** [comment]
I don't think so Zak; the new code would be exercised by anything that uses connect, including the tests as they are. The issue is that coverage metrics are not being tracked for this repo and so the check is failing because it's seeing 0% everywhere. We should investigate adding coverage metrics, but that's orthogonal to this and a task that should be prioritised separately and in my opinion shouldn't delay our merging this.

**Comment by zburke** [comment]
Hmmm; you're right @skomorokh. In [ui-users we pass `--coverage` as a test option](https://github.com/folio-org/ui-users/blob/master/Jenkinsfile#L9) to generate coverage info but that doesn't seem to work here.  I'll investigate.

**Pull request merged**
